export const GET_WEATHER = 'GET_WEATHER';
export const SET_WEEK_WEATHER = 'SET_WEEK_WEATHER';
export const GET_CITY_NAME = 'GET_CITY_NAME';
export const SET_DAILY_WEATHER = 'SET_DAILY_WEATHER';
export const GET_DAILY_EVENTS = 'GET_DAILY_EVENTS';
export const SET_DAILY_EVENTS = 'SET_DAILY_EVENTS';
export const CATCH_DAILY_EVENTS = 'CATCH_DAILY_EVENTS';
export const CATCH_WEATHER = 'CATCH_WEATHER';
