export const GET_WEEK_WEATHER = 'GET_WEEK_WEATHER';
export const SET_WEEK_WEATHER = 'SET_WEEK_WEATHER';
export const GET_CITY_NAME = 'GET_CITY_NAME';
export const SET_DAILY_WEATHER = 'SET_DAILY_WEATHER';
