export const actionNames = {
  GET_WEATHER: 'GET_WEATHER',
  SET_WEEK_WEATHER: 'SET_WEEK_WEATHER',
  GET_CITY_NAME: 'GET_CITY_NAME',
  SET_DAILY_WEATHER: 'SET_DAILY_WEATHER',
  GET_DAILY_EVENTS: 'GET_DAILY_EVENTS',
  SET_DAILY_EVENTS: 'SET_DAILY_EVENTS',
  CATCH_DAILY_EVENTS: 'CATCH_DAILY_EVENTS',
  CATCH_WEATHER: 'CATCH_WEATHER',
  SET_SPINNER: 'SET_SPINNER',
};
